# Generated by Django 3.2.8 on 2021-12-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='review',
            field=models.CharField(default='Review', max_length=5000),
        ),
    ]
