# Generated by Django 3.2.8 on 2021-12-18 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_user_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
