# Generated by Django 3.2.8 on 2021-12-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_book_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ID',
        ),
        migrations.AddField(
            model_name='book',
            name='auto_increment_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
