# Generated by Django 3.2.8 on 2021-12-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_auto_20211222_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='auto_increment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
